-- upgrade database from 3.2.1 to 3.2.2

-- bug 411
create index ts_defects_interval_TranSetIncarnationIdIndex on ts_defects_interval (ts_transet_incarnation_id);
create index ts_defects_interval_UserIncarnationIdIndex on ts_defects_interval (ts_user_incarnation_id);

create index ts_stats_tran_user_interval_TranSetIndex on ts_stats_tran_user_interval (ts_transet_id);
create index ts_stats_tran_user_interval_TranSetIncarnationIdIndex on ts_stats_tran_user_interval (ts_transet_incarnation_id);

create index ts_stats_transet_all_daily_TranSetIncarnationIdIndex on ts_stats_transet_all_daily (ts_transet_incarnation_id);
create index ts_stats_transet_all_interval_TranSetIncarnationIdIndex on ts_stats_transet_all_interval (ts_transet_incarnation_id);
create index ts_stats_transet_all_monthly_TranSetIncarnationIdIndex on ts_stats_transet_all_monthly (ts_transet_incarnation_id);
create index ts_stats_transet_all_weekly_TranSetIncarnationIdIndex on ts_stats_transet_all_weekly (ts_transet_incarnation_id);

create index ts_stats_transet_usergroup_daily_TranSetIncarnationIdIndex on ts_stats_transet_usergroup_daily (ts_transet_incarnation_id);
create index ts_stats_transet_usergroup_interval_TranSetIncarnationIdIndex on ts_stats_transet_usergroup_interval (ts_transet_incarnation_id);
create index ts_stats_transet_usergroup_monthly_TranSetIncarnationIdIndex on ts_stats_transet_usergroup_monthly (ts_transet_incarnation_id);
create index ts_stats_transet_usergroup_weekly_TranSetIncarnationIdIndex on ts_stats_transet_usergroup_weekly (ts_transet_incarnation_id);

create index ts_stats_transet_user_daily_TranSetIncarnationIdIndex on ts_stats_transet_user_daily (ts_transet_incarnation_id);
create index ts_stats_transet_user_daily_UserIncarnationIdIndex on ts_stats_transet_user_daily (ts_user_incarnation_id);
create index ts_stats_transet_user_interval_TranSetIncarnationIdIndex on ts_stats_transet_user_interval (ts_transet_incarnation_id);
create index ts_stats_transet_user_interval_UserIncarnationIdIndex on ts_stats_transet_user_interval (ts_user_incarnation_id);
create index ts_stats_transet_user_monthly_TranSetIncarnationIdIndex on ts_stats_transet_user_monthly (ts_transet_incarnation_id);
create index ts_stats_transet_user_monthly_UserIncarnationIdIndex on ts_stats_transet_user_monthly (ts_user_incarnation_id);
create index ts_stats_transet_user_weekly_TranSetIncarnationIdIndex on ts_stats_transet_user_weekly (ts_transet_incarnation_id);
create index ts_stats_transet_user_weekly_UserIncarnationIdIndex on ts_stats_transet_user_weekly (ts_user_incarnation_id);

create index ts_stats_tranunit_all_daily_TranSetIncarnationIdIndex on ts_stats_tranunit_all_daily (ts_transet_incarnation_id);
create index ts_stats_tranunit_all_interval_TranSetIncarnationIdIndex on ts_stats_tranunit_all_interval (ts_transet_incarnation_id);
create index ts_stats_tranunit_all_monthly_TranSetIncarnationIdIndex on ts_stats_tranunit_all_monthly (ts_transet_incarnation_id);
create index ts_stats_tranunit_all_weekly_TranSetIncarnationIdIndex on ts_stats_tranunit_all_weekly (ts_transet_incarnation_id);

create index ts_stats_tranunit_usergroup_daily_TranSetIncarnationIdIndex on ts_stats_tranunit_usergroup_daily (ts_transet_incarnation_id);
create index ts_stats_tranunit_usergroup_interval_TranSetIncarnationIdIndex on ts_stats_tranunit_usergroup_interval (ts_transet_incarnation_id);
create index ts_stats_tranunit_usergroup_monthly_TranSetIncarnationIdIndex on ts_stats_tranunit_usergroup_monthly (ts_transet_incarnation_id);
create index ts_stats_tranunit_usergroup_weekly_TranSetIncarnationIdIndex on ts_stats_tranunit_usergroup_weekly (ts_transet_incarnation_id);

create index ts_stats_tranunit_user_daily_TranSetIncarnationIdIndex on ts_stats_tranunit_user_daily (ts_transet_incarnation_id);
create index ts_stats_tranunit_user_daily_UserIncarnationIdIndex on ts_stats_tranunit_user_daily (ts_user_incarnation_id);
create index ts_stats_tranunit_user_interval_TranSetIncarnationIdIndex on ts_stats_tranunit_user_interval (ts_transet_incarnation_id);
create index ts_stats_tranunit_user_interval_UserIncarnationIdIndex on ts_stats_tranunit_user_interval (ts_user_incarnation_id);
create index ts_stats_tranunit_user_monthly_TranSetIncarnationIdIndex on ts_stats_tranunit_user_monthly (ts_transet_incarnation_id);
create index ts_stats_tranunit_user_monthly_UserIncarnationIdIndex on ts_stats_tranunit_user_monthly (ts_user_incarnation_id);
create index ts_stats_tranunit_user_weekly_TranSetIncarnationIdIndex on ts_stats_tranunit_user_weekly (ts_transet_incarnation_id);
create index ts_stats_tranunit_user_weekly_UserIncarnationIdIndex on ts_stats_tranunit_user_weekly (ts_user_incarnation_id);

\echo Updating database version
update ts_domains set ts_db_versions='3.2.2';
